function [  ] = writeIndvOutput( currentFile, fileNum, badChannels, epochNum, horizFails, numGenFails, meanHEOG)
%Writes summary statistics of the preprocessing procedure to a .mat file
%Inputs:    currentFile = path of the input file
%           fileNum = number indicating which file form the current
%           experiment is being processed
%           badChannels = list of channels identified as bad and
%           interpolated by the pipeline
%           spochNum = number of epochs generated by the pipeline
%           horizFails = number of epochs which were identified as
%           containing excessive eye movements
%           numGenFails = number of epochs which were identified as
%           containing excessive artifact
%           meanHROG = mean voltage value in the HEOG channel

%get the path to the data folder
[filePath] = fileparts(currentFile);
%load the indivbidual info structure if it exists
if exist(strcat(filePath,'\Output\IndividualInfo.mat'), 'file')
load(strcat(filePath,'\Output\IndividualInfo.mat'));
end

%add current participant values to the IndividualInfo struct
IndividualInfo.badChannels{fileNum,1} = badChannels;
IndividualInfo.epochNum(fileNum,1) = epochNum;
IndividualInfo.horizFails{fileNum,1} = horizFails;
IndividualInfo.numGenFails(fileNum,1) = numGenFails;
IndividualInfo.meanHEOG(fileNum,1) = meanHEOG;

save(strcat(filePath,'\Output\IndividualInfo.mat'),'IndividualInfo')

end