function [ IndividualInfo ] = writeIndvOutput( currentFile, badChannels, epochNum, horizFails, numGenFails, meanHEOG)
%Writes summary statistics of the preprocessing procedure to a .mat file
%Inputs:    currentFile = path of the input file
%           fileNum = number indicating which file form the current
%           experiment is being processed
%           badChannels = list of channels identified as bad and
%           interpolated by the pipeline
%           spochNum = number of epochs generated by the pipeline
%           horizFails = number of epochs which were identified as
%           containing excessive eye movements
%           numGenFails = number of epochs which were identified as
%           containing excessive artifact
%           meanHEOG = mean voltage value in the HEOG channel
%Outputs:   IndividualInfo = struct which holds all of the input variables

%get the path to the data folder
[filePath, fileName] = fileparts(currentFile);

%add current participant values to the IndividualInfo struct
IndividualInfo.badChannels = badChannels;
IndividualInfo.epochNum = epochNum;
IndividualInfo.horizFails = horizFails;
IndividualInfo.numGenFails = numGenFails;
IndividualInfo.meanHEOG = meanHEOG;

%Save into the processingInfo folder
save(strcat(filePath,'\Output\ProcessingInfo\',fileName,'-IndividualInfo.mat'),'IndividualInfo')

end